server:
  port: 8762
eureka:
  instance:
    hostname: qf2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@qf1:8761/eureka
  server:
    #不要保护模式
    enable-self-preservation: false
spring:
  security:
    user:
      name: root
      password: root