spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19940206
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
mybatis:
  mapper-locations: classpath*:com/test/bike/dao/mapper/*.xml
  type-aliases-package: com.test.bike.pojo