spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19940206
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
mybatis:
  mapper-locations: classpath*:com/test/bike/dao/mapper/*.xml
  type-aliases-package: com.test.bike.pojo
dubbo:
  application:
    name: bike-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://www.vm.com:2181
  scan:
    base-packages: com.test.bike.service
server:
  port: 8080