server:
  port: 9200
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/caowei668/configs.git
          search-paths: configs
          username: 13343533950
          password: 19940206wscw
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true