#spring.datasource.driver=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
#spring.datasource.username=root
#spring.datasource.password=19940206

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 19940206
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html
      prefix:
  thymeleaf:
    mode: LEGACYHTML5
server:
  port: 8080
mybatis:
  type-aliases-package: com.test.boot.pojo
  mapper-locations: classpath:com/test/boot/dao/mapper/*.xml